if(WIN32)

	set(CMAKE_CXX_FLAGS "/W3 /EHsc")
	set(CMAKE_CXX_FLAGS_DEBUG "/D_DEBUG /MTd /Zi /Od /RTC1")
	set(CMAKE_CXX_FLAGS_MINSIZEREL "/MT /O1 /Oi /Os /GL /Gy /D NDEBUG")
	set(CMAKE_CXX_FLAGS_RELEASE "/MT /O1 /Oi /Os /GL /Gy /D NDEBUG")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/MT /Zi /O1 /Oi /Os /GL /Gy /D NDEBUG")

	set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /OPT:REF /OPT:ICF /SAFESEH:NO /LTCG")
	set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /OPT:REF /OPT:ICF /SAFESEH:NO /LTCG")
	set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} /LTCG")

	add_definitions(-DNOMINMAX -DWIN32 -DUNICODE -D_UNICODE)

else()

endif()