set(CMAKE_CXX_FLAGS "/W3 /EHsc")
set(CMAKE_CXX_FLAGS_DEBUG "/D_DEBUG /MTd /Zi /Od /RTC1")
set(CMAKE_CXX_FLAGS_MINSIZEREL "/MT /O1 /Oi /Os /GL /Gy /D NDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE "/MT /O1 /Oi /Os /GL /Gy /D NDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/MT /Zi /O1 /Oi /Os /GL /Gy /D NDEBUG")

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /OPT:REF /OPT:ICF /SAFESEH:NO /LTCG")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /OPT:REF /OPT:ICF /SAFESEH:NO /LTCG")
set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} /LTCG")


if(CMAKE_BUILD_TYPE EQUAL "Release")
	set_property(DIRECTORY APPEND PROPERTY COMPILE_DEFINITIONS
		NOMINMAX;
		WIN32;
		UNICODE;
		_UNICODE;
		_CRT_SECURE_NO_WARNINGS;
		MAKI_OS_WIN=1;
		MAKI_USE_SIMD=1;
		MAKI_SIMD_ALIGN=16;
		MAKI_CACHE_ALIGN=64;
		MAKI_SORT_DRAW_COMMANDS_IN_RENDER_THREAD=0;
		MAKI_PROFILING=0;
		MAKI_CONSOLE_OUTPUT_ENABLED=0;
	)
else()
	set_property(DIRECTORY APPEND PROPERTY COMPILE_DEFINITIONS
		NOMINMAX;
		WIN32;
		UNICODE;
		_UNICODE;
		_CRT_SECURE_NO_WARNINGS;
		MAKI_OS_WIN=1;
		MAKI_USE_SIMD=1;
		MAKI_SIMD_ALIGN=16;
		MAKI_CACHE_ALIGN=64;
		MAKI_SORT_DRAW_COMMANDS_IN_RENDER_THREAD=0;
		MAKI_PROFILING=0;
		MAKI_CONSOLE_OUTPUT_ENABLED=1;
	)
endif()
